CREATE TABLE IF NOT EXISTS ai_runtime_events (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 user_id BIGINT UNSIGNED NULL,
 route VARCHAR(60) NOT NULL,
 model VARCHAR(120) NULL,
 duration_ms INT UNSIGNED NULL,
 success TINYINT(1) NOT NULL DEFAULT 1,
 error_message VARCHAR(500) NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL,
 INDEX idx_ai_runtime_created(created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
